### ISSUE TITLE
Rapp example doesn't work on MacOS Arm M1

### ISSUE THREAD

**Issue by JosiahParry** [r-lib/Rapp#3]
I am running the example from the README and it doesn't appear to work. I assume there is more setup required than is documented.

Steps I took :

1. Create a new directory
2. create a new file `flip-coin.R`
3. Copy contents 
4. From terminal `chmod +x flip-coin.R`
5. Run `flip-coin` this fails with `command not found`
6. Run `./flip-coin.R` this fails with `env: Rapp: No such file or directory`

Any tips?

**Comment by JosiahParry** [comment]
Note that the script does work with `Rapp::run("flip-coin.R")`

**Comment by t-kalinowski** [comment]
`Rapp` needs to be on the `PATH`. Place something like this in `.zprofile` (assuming you're using the default zsh shell) 

```r
export PATH=$(Rscript -e 'cat(system.file("exec", package = "Rapp"))'):$PATH
```

For the next release, we should export a `Rapp::install_apps()` function that places symlinks from `~/bin/<apps>` to the R package `exec`.

**Comment by JosiahParry** [comment]
Gotcha. I followed the instructions from the "using in an R package" section and that helped. Perhaps the bit about adding Rapp to the path should be included more generally outside of the context of use in an R package. 
This lets it be called as `./flip-coin.R` successfully! Though not as its own CLI too. 

Having an `Rapp::install_rapp()` and an `Rapp::install_app()` would be very handy.

**Comment by JosiahParry** [comment]
Sorry, now I'm commandeering the issue! For use on Windows, should the output of `system.file("exec", package = "Rapp")` be included as a PATH environment variable?

closing though because it seems this is known and the issue is about installing the executable

**Comment by t-kalinowski** [comment]
Regarding the Windows question, I have this towards the end of the Readme:

> # Windows
> 
> Rapp works on Windows. However, because there is no native support for
> `!#` shebang executable on Windows, you must invoke Rapp directly.
> 
> ``` cmd
> Rapp flip-coin --n 3
> ```

The actual implementation of windows `Rapp` is here: https://github.com/r-lib/Rapp/blob/main/exec/Rapp.cmd

I remember thinking about this quite deeply, but I could not figure out a way to recreate the same shebang-like experience on Windows. (Let me know if you have any ideas!) Note that Python faced a similar question and also ended up writing a separate front-end:  https://docs.python.org/3/using/windows.html#python-launcher-for-windows, which still doesn't get to usage as nice as Unix `#!` shebang files allow.

**Comment by JosiahParry** [comment]
Yes. I got this working on windows! Though I do not think that Rapp will work with omitting the extension from the file. I've added the file path to the PATH as well as created another environment variable with the name of the file without .R which is a path to the variable. 

Would you mind pointing me to the source code where the search logic is? I could probably figure it out from there
